### ISSUE TITLE
RFC: Store SiteID on each DataObject type for easier extraction

### ISSUE THREAD

**Issue by SilbinaryWolf** [symbiote/silverstripe-multisites#77]
Hard to say if this is definitely a good idea or not, but storing the current SiteID when a File / any DataObject is saved would make pulling out an entire Site a trivial task.

Thoughts?

**Comment by nyeholt** [comment]
There's a `MultisitesAware` extension already - does that do what you need?

**Comment by SilbinaryWolf** [comment]
Needs to work out of the box ideally... We're going to assume people aren't going to put the effort in adding that to every DataObject themselves.

My other thought would perhaps be a SS_Report that tells you all the DataObjects used under a SiteID.
You could determine this by iterating over each DataObject type, look for a "SiteTree"/"Page"/etc has_one/has_many/many_many, and determine if they belong to a specific SiteID like that for extraction.

**Comment by nyeholt** [comment]
But I'm not convinced that SiteID on _every_ data object is a good idea. The next path down that road is to having augmentSql then filter all queries for those data objects and automatically filter by SiteID - and that way lies all kinds of magic worm cans I don't want opened. 

It's not applied by default because you _should_ be thinking about the implications of what you're doing and what you're hoping to achieve by having it applied.

**Comment by SilbinaryWolf** [comment]
I agree now.
